const APP_TITLE = 'UERM PHILHEALTH CF4'
const APP_FOOTER_LABEL = 'POWERED BY UERM IT DEPARTMENT'
const FILTER_ERROR = 'SORRY, NO RECORD FOUND. PLEASE TRY AGAIN'
const API_ERROR = 'API CONNECTION ERROR. PLEASE CONTACT THE IT DEPARTMENT'
const SEARCH_BY_LASTNAME_CASENO = 'CASE NO / LASTNAME'
const SEARCH_BY_DATE_AD = 'DATE ADMITTED'
const SEARCH_BY_DATE = 'DATE ADMITTED / DATE DISCHARGED'
const SEARCH_BY_DATE_DISCHARGED = 'DATE DISCHARGED'
const SEARCH_LABEL = 'SEARCH'
const INPUT_RULE = 'Sorry, Minimum is 2 Letters'
const NAME_OF_HCI = 'UNIVERSITY OF THE EAST RAMON MAGSAYSAY MEMORIAL MEDICAL CENTER INC (UERMMMCI)'
const ACCREDITATION_NO = 'H93005943'
const ADDRESS_OF_HCI = '#64 AURORA BOULEVARD BARANGAY DOÑA IMELDA, QUEZON CITY 1113'
const ADDRESS_BOTTOM_LABEL = 'Bldg. No and Name / Lot / Block / Street / Subdivision / Village / Barangay/City / Municipality / Province / ZIP Code'
const BUTTON_CF4_LABEL = 'CREATE CF4'
const LOADING_LABEL = 'FETCHING DATA'
const AD_DIALOG_LABEL = 'ADMITTING DIAGNOSIS'
const HISTORY_DIALOG_LABEL = 'HISTORY OF PRESENT ILLNESS'
const PERTINENT_PAST_MEDICAL_HISTORY_DIALOG_LABEL = 'PERTINENT PAST MEDICAL HISTORY'
const NEW_AD_STATUS = 'NEW ENTRY'
const FORM_SUBMIT_MESSAGE = 'ADMITTING DIAGNOSIS WAS SUBMITTED'
const CREATE_CF4_MESSAGE = 'PATIENT CF4 WAS CREATED'
const FORM_SUBMIT_HISTORY_MESSAGE = 'HISTORY OF PRESENT ILLNESS WAS SUBMITTED'
const FORM_UPDATE_HISTORY_MESSAGE = 'HISTORY OF PRESENT ILLNESS WAS UPDATED'
const FORM_UPDATE_PERTINENT_HISTORY_MESSAGE = 'PERTINENT PAST MEDICAL HISTORY WAS UPDATED'
const FORM_UPDATE_PATIENT_DATA_MESSAGE = 'PATIENT DATA WAS UPDATED'
const FORM_UPDATE_REASON_FOR_ADMISSION_MESSAGE = 'REASON FOR ADMISSION WAS UPDATED'
const FORM_UPDATE_COURSE_IN_THE_WARD_MESSAGE = 'COURSE IN THE WARD WAS UPDATED'
const FORM_UPDATE_OUTCOME_OF_TREATMENT_MESSAGE = 'OUTCOME OF TREATMENT WAS UPDATED'

export default {
  APP_TITLE,
  APP_FOOTER_LABEL,
  FILTER_ERROR,
  API_ERROR,
  SEARCH_BY_LASTNAME_CASENO,
  SEARCH_BY_DATE,
  SEARCH_BY_DATE_AD,
  SEARCH_BY_DATE_DISCHARGED,
  SEARCH_LABEL,
  INPUT_RULE,
  NAME_OF_HCI,
  ACCREDITATION_NO,
  ADDRESS_OF_HCI,
  ADDRESS_BOTTOM_LABEL,
  BUTTON_CF4_LABEL,
  LOADING_LABEL,
  AD_DIALOG_LABEL,
  HISTORY_DIALOG_LABEL,
  NEW_AD_STATUS,
  FORM_SUBMIT_MESSAGE,
  FORM_SUBMIT_HISTORY_MESSAGE,
  FORM_UPDATE_HISTORY_MESSAGE,
  FORM_UPDATE_PATIENT_DATA_MESSAGE,
  PERTINENT_PAST_MEDICAL_HISTORY_DIALOG_LABEL,
  FORM_UPDATE_PERTINENT_HISTORY_MESSAGE,
  CREATE_CF4_MESSAGE,
  FORM_UPDATE_REASON_FOR_ADMISSION_MESSAGE,
  FORM_UPDATE_COURSE_IN_THE_WARD_MESSAGE,
  FORM_UPDATE_OUTCOME_OF_TREATMENT_MESSAGE
}
